# making a ingress controller
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.ingress.host }}.doctorsingh.shop
    http:
      paths:
      - path: /
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: {{ include "hello-world.fullname" . }}
            port:
              number: {{ .Values.ingress.portNumber }}
