name: helm deploy to gke cluster
on:
  push:
    branches:
      - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v2
          with:
            project_id: hybrid-circle-420710
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            export_default_credentials: true
        - name: configure azure helm repo
          uses: azure/setup-helm@v4.2.0
        - uses: google-github-actions/get-gke-credentials@v2
          with:
            cluster_name: cluster-new
            location: 'us-central1'
        - name: helm install
          run: |
            helm upgrade --install myapp ./charts/hello-world/ --namespace test --create-namespace 
            kubectl get pods