name: helm deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Helm deploy - production
        if: github.ref == 'refs/heads/main'
        run: |
          echo " production "
      - name: Helm deploy - development
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "development"
